#!/bin/sh
# ════════════════════════════════════════════════════════════════
# PHP Runtime Configuration Script
# ════════════════════════════════════════════════════════════════
#
# This script configures PHP settings based on php-settings.conf
# Run during Docker build to apply optimizations.
#

set -e

# Load configuration
# When running in Docker build, config is at /tmp/values-php
# Otherwise, load from root directory relative to script location
if [ -f "/tmp/values-php" ]; then
    CONFIG_FILE="/tmp/values-php"
else
    SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
    ROOT_DIR="$(dirname "$SCRIPT_DIR")"
    CONFIG_FILE="${ROOT_DIR}/values-php"
fi

if [ ! -f "$CONFIG_FILE" ]; then
    echo "❌ Error: values-php not found at $CONFIG_FILE"
    exit 1
fi

# Source configuration (extract key=value pairs, ignore comments)
eval "$(grep -E '^[A-Z_]+=' "$CONFIG_FILE")"

echo "🔧 Configuring PHP runtime..."

# ============================================================================
# Memory Configuration
# ============================================================================

cat > /usr/local/etc/php/conf.d/memory-limit.ini <<EOF
; Memory Configuration
; Generated by configure-php.sh

memory_limit=${PHP_MEMORY_LIMIT}
upload_max_filesize=${PHP_UPLOAD_MAX_FILESIZE}
post_max_size=${PHP_POST_MAX_SIZE}
max_execution_time=${PHP_MAX_EXECUTION_TIME}
max_input_time=${PHP_MAX_INPUT_TIME}
EOF

echo "✅ Memory limits configured"

# ============================================================================
# Performance Configuration
# ============================================================================

cat > /usr/local/etc/php/conf.d/performance.ini <<EOF
; Performance Configuration
; Generated by configure-php.sh

; Realpath cache - CRITICAL for performance (reduces stat() calls by ~70%)
realpath_cache_size=${REALPATH_CACHE_SIZE}
realpath_cache_ttl=${REALPATH_CACHE_TTL}

; Security & Production settings
expose_php=${PHP_EXPOSE_PHP}
display_errors=${PHP_DISPLAY_ERRORS}
log_errors=On
error_reporting=${PHP_ERROR_REPORTING}

; Output buffering
output_buffering=${PHP_OUTPUT_BUFFERING}

; Zend optimizations
zend.exception_ignore_args=${ZEND_EXCEPTION_IGNORE_ARGS}
zend.exception_string_param_max_len=${ZEND_EXCEPTION_STRING_PARAM_MAX_LEN}
EOF

echo "✅ Performance settings configured"

# ============================================================================
# OPcache with JIT Configuration
# ============================================================================

cat > /usr/local/etc/php/conf.d/opcache.ini <<EOF
; OPcache Configuration - Optimized for Laravel Octane + Swoole
; Generated by configure-php.sh

opcache.enable=1
opcache.enable_cli=1

; Memory settings - shared across all workers!
opcache.memory_consumption=${OPCACHE_MEMORY_CONSUMPTION}
opcache.interned_strings_buffer=${OPCACHE_INTERNED_STRINGS_BUFFER}
opcache.max_accelerated_files=${OPCACHE_MAX_ACCELERATED_FILES}

; Production optimizations - zero filesystem checks for maximum speed
opcache.validate_timestamps=0
opcache.revalidate_freq=0

; Performance optimizations
opcache.save_comments=1
opcache.fast_shutdown=1
opcache.enable_file_override=1

; Preloading support (configure in your app Dockerfile)
opcache.preload_user=www-data

; File cache disabled to save memory (we rely on shared memory only)
opcache.file_cache=

; JIT Compiler (PHP 8+)
opcache.jit_buffer_size=${JIT_BUFFER_SIZE}
opcache.jit=${JIT_MODE}
EOF

echo "✅ OPcache with JIT configured"

# ============================================================================
# Display Configuration Summary
# ============================================================================

echo ""
echo "📊 Configuration Summary:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Memory:"
echo "  PHP Memory Limit:      ${PHP_MEMORY_LIMIT}"
echo "  Upload/POST Max Size:  ${PHP_UPLOAD_MAX_FILESIZE} / ${PHP_POST_MAX_SIZE}"
echo ""
echo "OPcache (shared memory):"
echo "  Memory Consumption:    ${OPCACHE_MEMORY_CONSUMPTION}M"
echo "  Interned Strings:      ${OPCACHE_INTERNED_STRINGS_BUFFER}M"
echo "  Max Files:             ${OPCACHE_MAX_ACCELERATED_FILES}"
echo ""
echo "JIT Compiler:"
echo "  Buffer Size:           ${JIT_BUFFER_SIZE}"
echo "  Mode:                  ${JIT_MODE}"
echo ""
echo "Realpath Cache:"
echo "  Size:                  ${REALPATH_CACHE_SIZE}"
echo "  TTL:                   ${REALPATH_CACHE_TTL}s"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ PHP configuration complete!"